import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	guideSidebar: [
		{
			type: "category",
			label: "Getting Started",
			items: [
				"getting-started/prerequisites",
				"getting-started/installation",
				"getting-started/running-locally",
				"getting-started/project-overview",
			],
		},
		{
			type: "category",
			label: "Architecture",
			items: [
				"architecture/monorepo-structure",
				"architecture/turborepo-pipeline",
				"architecture/package-dependency-graph",
				"architecture/cms-content-flow",
				"architecture/i18n-routing",
				"architecture/caching-strategy",
			],
		},
		{
			type: "category",
			label: "Packages",
			items: [
				"packages/app-config",
				"packages/wagtail-api-client",
				"packages/wagtail-cms-types",
				"packages/wagtail-cms-mapping",
				"packages/i18n",
				"packages/logger",
				"packages/shared-configs",
			],
		},
		{
			type: "category",
			label: "App Guide",
			items: [
				"app-guide/app-structure",
				"app-guide/routing",
				"app-guide/layouts-and-error-boundaries",
				"app-guide/cms-page-rendering",
				"app-guide/adding-block-components",
				"app-guide/adding-page-types",
				"app-guide/analytics-integration",
				"app-guide/seo-and-metadata",
				"app-guide/security-headers",
			],
		},
		{
			type: "category",
			label: "Deployment",
			items: [
				"deployment/environment-variables",
				"deployment/docker-build",
				"deployment/ci-cd-pipeline",
				"deployment/github-pages-docs",
				"deployment/troubleshooting",
			],
		},
		{
			type: "category",
			label: "Onboarding Sites",
			items: ["onboarding-sites/index"],
		},
	],
	apiSidebar: [
		{
			type: "category",
			label: "API Reference",
			items: [
				{
					type: "autogenerated",
					dirName: "api",
				},
			],
		},
	],
};

export default sidebars;
